spring.application.name=task2-receitas

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/receitas}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Postgres}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

spring.thymeleaf.cache=${SPRING_THYMELEAF_CACHE:false}
server.port=${SERVER_PORT:8080}

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${EMAIL:}
spring.mail.password=${SENHA_EMAIL:}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS_ENABLE:true}