spring.application.name=task2-receitas
spring.datasource.url=jdbc:postgresql://localhost:5432/receitas
spring.datasource.username=postgres
spring.datasource.password=Postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8080